ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS country TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS gender TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS location TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS image_url TEXT NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS is_new BOOLEAN NOT NULL DEFAULT false;
